
package uni.aed.gui;
import javax.swing.JOptionPane;
import uni.aed.BigInteger.EnteroMuyGrande;

public class FrmEnteroMuyGrande extends javax.swing.JFrame {

    /**
     * Creates new form EnteroMuyGrande
     */
    public FrmEnteroMuyGrande() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrimerNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSegundoNumero = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnInvertir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnMulSim = new javax.swing.JButton();
        btnMulLarg = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnDivSim = new javax.swing.JButton();
        DivLarg = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ingresa el primer número:");

        jLabel2.setText("Ingresa el segundo número:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnInvertir.setText("Invertir");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSegundoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtPrimerNumero)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnInvertir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvertir)
                    .addComponent(btnLimpiar))
                .addGap(81, 81, 81))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operaciones suma y resta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestar)
                    .addComponent(btnSumar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnSumar)
                .addGap(18, 18, 18)
                .addComponent(btnRestar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operación multiplicación:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnMulSim.setText("Simplista");
        btnMulSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulSimActionPerformed(evt);
            }
        });

        btnMulLarg.setText("Larga");
        btnMulLarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulLargActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMulSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMulLarg)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMulSim)
                    .addComponent(btnMulLarg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operación división", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnDivSim.setText("Simplista");
        btnDivSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivSimActionPerformed(evt);
            }
        });

        DivLarg.setText("Larga");
        DivLarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivLargActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDivSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(DivLarg)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivSim)
                    .addComponent(DivLarg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();
    
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
                "MENSAJE",JOptionPane.WARNING_MESSAGE);
        return;
    }     
    EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
    EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
    
    EnteroMuyGrande resultado = numero1.suma(numero2);
    
    txtResultado.setText(resultado.aString());
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed

    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();
    
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
                "MENSAJE",JOptionPane.WARNING_MESSAGE);
        return;
    }     
    EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
    EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
    
    EnteroMuyGrande resultado = numero1.resta(numero2);
    
    txtResultado.setText(resultado.aString());
        
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMulSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulSimActionPerformed
    // Obtener los números ingresados como cadenas desde los campos de texto
    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();

    // Verificar si se han ingresado números
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
                "MENSAJE",JOptionPane.WARNING_MESSAGE);
        return;
    }


        // Convertir las cadenas a BigIntegers y realizar la multiplicación
        EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
        EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
        EnteroMuyGrande resultado = numero1.multiplicacionSimplista(numero2);

        // Mostrar el resultado en el campo de resultado
        txtResultado.setText(resultado.aString());

    

    }//GEN-LAST:event_btnMulSimActionPerformed

    private void ClearAll(){
        txtPrimerNumero.setText("");
        txtSegundoNumero.setText("");
        txtResultado.setText("");        
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        ClearAll();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMulLargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulLargActionPerformed
    // Obtener los números ingresados como cadenas desde los campos de texto
    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();

    // Verificar si se han ingresado números
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
            "MENSAJE", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Convertir las cadenas a EnteroMuyGrande y realizar la multiplicación
    EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
    EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
    
    EnteroMuyGrande resultado = numero1.multiplicacionLarga(numero2);

    // Mostrar el resultado en el campo de resultado
    txtResultado.setText(resultado.aString());        
    }//GEN-LAST:event_btnMulLargActionPerformed

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
        String strNumero1 = txtPrimerNumero.getText();

        // Verificar si se ha ingresado un número
        if (strNumero1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un número en el primer campo.", 
                "MENSAJE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convertir la cadena a EnteroMuyGrande y llamar al método para invertir la lista
        EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
        numero1.invertir();

        // Mostrar el número invertido en el campo txtPrimerNumero
        txtResultado.setText(numero1.aString());  
    }//GEN-LAST:event_btnInvertirActionPerformed

    private void btnDivSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivSimActionPerformed
    // Obtener los números ingresados como cadenas desde los campos de texto
    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();

    // Verificar si se han ingresado números
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
            "MENSAJE", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Convertir las cadenas a EnteroMuyGrande y realizar la multiplicación
    EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
    EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
    
    EnteroMuyGrande resultado = numero1.divisionSimplista(numero2);

    // Mostrar el resultado en el campo de resultado
    txtResultado.setText(resultado.aString());  
    }//GEN-LAST:event_btnDivSimActionPerformed

    private void DivLargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivLargActionPerformed
    // Obtener los números ingresados como cadenas desde los campos de texto
    String strNumero1 = txtPrimerNumero.getText();
    String strNumero2 = txtSegundoNumero.getText();

    // Verificar si se han ingresado números
    if (strNumero1.isEmpty() || strNumero2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa dos números.", 
            "MENSAJE", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Convertir las cadenas a EnteroMuyGrande y realizar la multiplicación
    EnteroMuyGrande numero1 = new EnteroMuyGrande(strNumero1);
    EnteroMuyGrande numero2 = new EnteroMuyGrande(strNumero2);
    
    EnteroMuyGrande resultado = numero1.divisionLarga(numero2);

    // Mostrar el resultado en el campo de resultado
    txtResultado.setText(resultado.aString());  
    }//GEN-LAST:event_DivLargActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEnteroMuyGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEnteroMuyGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEnteroMuyGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEnteroMuyGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEnteroMuyGrande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DivLarg;
    private javax.swing.JButton btnDivSim;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMulLarg;
    private javax.swing.JButton btnMulSim;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtPrimerNumero;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
